'''
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DO NOT EDIT THIS FILE
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'''

import io
from unittest import mock, TestCase

from nba_stats import three_pointer_calculations, process_laker_data


class TestNbaStats(TestCase):

    @mock.patch('sys.stdout', new_callable=io.StringIO)
    def test_three_pointer_calculations(self, mock_stdout):
        three_pointer_calculations()

        self.assertEqual(
            "Jamal Murray: 46, Fred VanVleet: 43, James Harden: 37\nJamal Murray's three point percentage is 49%. Fred VanVleet's three point percentage is 39%. James Harden's three point percentage is 34%.\n",
            mock_stdout.getvalue()
        )